// Generated by odin.dust (version 0.3.11) - do not edit
template <typename real_type, typename container>
__host__ __device__ real_type odin_sum1(const container x, size_t from, size_t to);
template <typename real_type, typename container>
__host__ __device__ real_type odin_sum2(const container x, int from_i, int to_i, int from_j, int to_j, int dim_x_1);
template <typename real_type, typename T, typename U>
__host__ __device__ real_type fintdiv(T x, U y) {
  return std::floor(x / y);
}

template <typename real_type, typename T, typename U>
__host__ __device__ real_type fmodr(T x, U y) {
  real_type tmp = std::fmod(static_cast<real_type>(x),
                            static_cast<real_type>(y));
  if (tmp * y < 0) {
    tmp += y;
  }
  return tmp;
}

// These exist to support the model on the gpu, as in C++14 std::min
// and std::max are constexpr and error without --expt-relaxed-constexpr
template <typename T>
__host__ __device__ T odin_min(T x, T y) {
  return x < y ? x : y;
}

template <typename T>
__host__ __device__ T odin_max(T x, T y) {
  return x > y ? x : y;
}

template <typename T>
__host__ __device__ T odin_sign(T x) {
  return (x > 0) ? 1 : ((x < 0) ? -1 : 0);
}
// [[dust::class(model_targeted_vax)]]
// [[dust::time_type(discrete)]]
// [[dust::param(beta_h, has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(beta_z, has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(CFR, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(D0, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(daily_doses, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(Ea0, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(Eb0, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(gamma_E, has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(gamma_Id, has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(gamma_Ir, has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(Id0, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(Ir0, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(m, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(n_group, has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(N_prioritisation_steps, has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(n_vax, has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(prioritisation_strategy, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(R0, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(S0, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(vaccination_campaign_length, has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(vaccination_coverage_target, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(vaccine_uptake, has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(ve_I, has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(ve_T, has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(dt, has_default = TRUE, default_value = 1L, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
class model_targeted_vax {
public:
  using real_type = double;
  using rng_state_type = dust::random::generator<real_type>;
  using data_type = dust::no_data;
  struct shared_type {
    real_type beta_h;
    std::vector<real_type> beta_z;
    std::vector<real_type> CFR;
    std::vector<real_type> D0;
    std::vector<real_type> daily_doses;
    int dim_beta_z;
    int dim_CFR;
    int dim_CFR_1;
    int dim_CFR_2;
    int dim_D;
    int dim_D_1;
    int dim_D_2;
    int dim_D0;
    int dim_D0_1;
    int dim_D0_2;
    int dim_daily_doses;
    int dim_daily_doses_1;
    int dim_daily_doses_2;
    int dim_daily_doses_t;
    int dim_daily_doses_t_1;
    int dim_daily_doses_t_2;
    int dim_delta_D;
    int dim_delta_D_1;
    int dim_delta_D_2;
    int dim_delta_Ea;
    int dim_delta_Ea_1;
    int dim_delta_Ea_2;
    int dim_delta_Ea_n_vaccination;
    int dim_delta_Ea_n_vaccination_1;
    int dim_delta_Ea_n_vaccination_2;
    int dim_delta_Eb;
    int dim_delta_Eb_1;
    int dim_delta_Eb_2;
    int dim_delta_Eb_n_vaccination;
    int dim_delta_Eb_n_vaccination_1;
    int dim_delta_Eb_n_vaccination_2;
    int dim_delta_Id;
    int dim_delta_Id_1;
    int dim_delta_Id_2;
    int dim_delta_Ir;
    int dim_delta_Ir_1;
    int dim_delta_Ir_2;
    int dim_delta_R;
    int dim_delta_R_1;
    int dim_delta_R_2;
    int dim_delta_R_n_vaccination;
    int dim_delta_R_n_vaccination_1;
    int dim_delta_R_n_vaccination_2;
    int dim_delta_S_n_vaccination;
    int dim_delta_S_n_vaccination_1;
    int dim_delta_S_n_vaccination_2;
    int dim_E;
    int dim_E_1;
    int dim_E_2;
    int dim_Ea;
    int dim_Ea_1;
    int dim_Ea_2;
    int dim_Ea0;
    int dim_Ea0_1;
    int dim_Ea0_2;
    int dim_Eb;
    int dim_Eb_1;
    int dim_Eb_2;
    int dim_Eb0;
    int dim_Eb0_1;
    int dim_Eb0_2;
    int dim_I;
    int dim_I_1;
    int dim_I_2;
    int dim_I_infectious;
    int dim_I_infectious_1;
    int dim_I_infectious_2;
    int dim_Id;
    int dim_Id_1;
    int dim_Id_2;
    int dim_Id0;
    int dim_Id0_1;
    int dim_Id0_2;
    int dim_Ir;
    int dim_Ir_1;
    int dim_Ir_2;
    int dim_Ir0;
    int dim_Ir0_1;
    int dim_Ir0_2;
    int dim_lambda;
    int dim_lambda_1;
    int dim_lambda_2;
    int dim_m;
    int dim_m_1;
    int dim_m_2;
    int dim_N;
    int dim_N_1;
    int dim_N_2;
    int dim_n_EaEb;
    int dim_n_EaEb_1;
    int dim_n_EaEb_2;
    int dim_n_EbI;
    int dim_n_EbI_1;
    int dim_n_EbI_2;
    int dim_n_EbId;
    int dim_n_EbId_1;
    int dim_n_EbId_2;
    int dim_n_EbIr;
    int dim_n_EbIr_1;
    int dim_n_EbIr_2;
    int dim_n_eligible;
    int dim_n_IdD;
    int dim_n_IdD_1;
    int dim_n_IdD_2;
    int dim_n_IrR;
    int dim_n_IrR_1;
    int dim_n_IrR_2;
    int dim_n_SEa;
    int dim_n_SEa_1;
    int dim_n_SEa_2;
    int dim_n_vaccination_t_Ea;
    int dim_n_vaccination_t_Ea_1;
    int dim_n_vaccination_t_Ea_2;
    int dim_n_vaccination_t_Eb;
    int dim_n_vaccination_t_Eb_1;
    int dim_n_vaccination_t_Eb_2;
    int dim_n_vaccination_t_R;
    int dim_n_vaccination_t_R_1;
    int dim_n_vaccination_t_R_2;
    int dim_n_vaccination_t_S;
    int dim_n_vaccination_t_S_1;
    int dim_n_vaccination_t_S_2;
    int dim_p_SE;
    int dim_p_SE_1;
    int dim_p_SE_2;
    int dim_prioritisation_strategy;
    int dim_prioritisation_strategy_1;
    int dim_prioritisation_strategy_2;
    int dim_prop_infectious;
    int dim_R;
    int dim_R_1;
    int dim_R_2;
    int dim_R0;
    int dim_R0_1;
    int dim_R0_2;
    int dim_S;
    int dim_S_1;
    int dim_S_2;
    int dim_s_ij;
    int dim_s_ij_1;
    int dim_s_ij_2;
    int dim_S0;
    int dim_S0_1;
    int dim_S0_2;
    int dim_target_met_t;
    int dim_target_met_t_1;
    int dim_target_met_t_2;
    int dim_total_vaccinated_t;
    int dim_total_vaccinated_t_1;
    int dim_total_vaccinated_t_2;
    int dim_vaccination_coverage_target;
    int dim_vaccination_coverage_target_1;
    int dim_vaccination_coverage_target_2;
    int dim_vaccine_uptake;
    int dim_ve_I;
    int dim_ve_T;
    real_type dt;
    std::vector<real_type> Ea0;
    std::vector<real_type> Eb0;
    real_type gamma_E;
    real_type gamma_Id;
    real_type gamma_Ir;
    std::vector<real_type> Id0;
    real_type initial_cases;
    real_type initial_cases_0_5;
    real_type initial_cases_15_plus;
    real_type initial_cases_5_15;
    real_type initial_cases_PBS;
    real_type initial_cases_SW;
    std::vector<real_type> initial_D;
    real_type initial_D_tot;
    real_type initial_deaths;
    real_type initial_deaths_0_5;
    real_type initial_deaths_15_plus;
    real_type initial_deaths_5_15;
    real_type initial_deaths_PBS;
    real_type initial_deaths_SW;
    std::vector<real_type> initial_E;
    real_type initial_E_tot;
    std::vector<real_type> initial_Ea;
    std::vector<real_type> initial_Eb;
    std::vector<real_type> initial_I;
    real_type initial_I_tot;
    std::vector<real_type> initial_Id;
    std::vector<real_type> initial_Ir;
    std::vector<real_type> initial_N;
    real_type initial_N_tot;
    real_type initial_prioritisation_step;
    std::vector<real_type> initial_R;
    real_type initial_R_tot;
    std::vector<real_type> initial_S;
    real_type initial_S_tot;
    real_type initial_total_vax;
    real_type initial_vax_given_Ea;
    real_type initial_vax_given_Eb;
    real_type initial_vax_given_R;
    real_type initial_vax_given_S;
    std::vector<real_type> Ir0;
    std::vector<real_type> m;
    int n_group;
    int N_prioritisation_steps;
    int n_vax;
    int offset_variable_D;
    int offset_variable_E;
    int offset_variable_Ea;
    int offset_variable_Eb;
    int offset_variable_I;
    int offset_variable_Id;
    int offset_variable_Ir;
    int offset_variable_N;
    int offset_variable_R;
    real_type p_EE;
    real_type p_EI;
    real_type p_IdD;
    real_type p_IrR;
    std::vector<real_type> prioritisation_strategy;
    std::vector<real_type> R0;
    std::vector<real_type> S0;
    real_type steps_per_week;
    int vaccination_campaign_length;
    std::vector<real_type> vaccination_coverage_target;
    std::vector<real_type> vaccine_uptake;
    std::vector<real_type> ve_I;
    std::vector<real_type> ve_T;
  };
  struct internal_type {
    std::vector<real_type> daily_doses_t;
    std::vector<real_type> delta_D;
    std::vector<real_type> delta_Ea;
    std::vector<real_type> delta_Ea_n_vaccination;
    std::vector<real_type> delta_Eb;
    std::vector<real_type> delta_Eb_n_vaccination;
    std::vector<real_type> delta_Id;
    std::vector<real_type> delta_Ir;
    std::vector<real_type> delta_R;
    std::vector<real_type> delta_R_n_vaccination;
    std::vector<real_type> delta_S_n_vaccination;
    std::vector<real_type> I_infectious;
    real_type initial_time;
    std::vector<real_type> lambda;
    std::vector<real_type> n_EaEb;
    std::vector<real_type> n_EbI;
    std::vector<real_type> n_EbId;
    std::vector<real_type> n_EbIr;
    std::vector<real_type> n_eligible;
    std::vector<real_type> n_IdD;
    std::vector<real_type> n_IrR;
    std::vector<real_type> n_SEa;
    std::vector<real_type> n_vaccination_t_Ea;
    std::vector<real_type> n_vaccination_t_Eb;
    std::vector<real_type> n_vaccination_t_R;
    std::vector<real_type> n_vaccination_t_S;
    std::vector<real_type> p_SE;
    std::vector<real_type> prop_infectious;
    std::vector<real_type> s_ij;
    std::vector<real_type> target_met_t;
    std::vector<real_type> total_vaccinated_t;
  };
  model_targeted_vax(const dust::pars_type<model_targeted_vax>& pars) :
    shared(pars.shared), internal(pars.internal) {
  }
  size_t size() const {
    return shared->dim_D + shared->dim_E + shared->dim_Ea + shared->dim_Eb + shared->dim_I + shared->dim_Id + shared->dim_Ir + shared->dim_N + shared->dim_R + shared->dim_S + 25;
  }
  std::vector<real_type> initial(size_t step, rng_state_type& rng_state) {
    std::vector<real_type> state(shared->dim_D + shared->dim_E + shared->dim_Ea + shared->dim_Eb + shared->dim_I + shared->dim_Id + shared->dim_Ir + shared->dim_N + shared->dim_R + shared->dim_S + 25);
    internal.initial_time = step;
    state[0] = internal.initial_time;
    state[1] = shared->initial_prioritisation_step;
    state[2] = shared->initial_cases;
    state[3] = shared->initial_deaths;
    state[4] = shared->initial_cases_0_5;
    state[5] = shared->initial_cases_5_15;
    state[6] = shared->initial_cases_15_plus;
    state[7] = shared->initial_cases_PBS;
    state[8] = shared->initial_cases_SW;
    state[9] = shared->initial_deaths_0_5;
    state[10] = shared->initial_deaths_5_15;
    state[11] = shared->initial_deaths_15_plus;
    state[12] = shared->initial_deaths_PBS;
    state[13] = shared->initial_deaths_SW;
    state[14] = shared->initial_vax_given_S;
    state[15] = shared->initial_vax_given_Ea;
    state[16] = shared->initial_vax_given_Eb;
    state[17] = shared->initial_vax_given_R;
    state[18] = shared->initial_S_tot;
    state[19] = shared->initial_E_tot;
    state[20] = shared->initial_I_tot;
    state[21] = shared->initial_R_tot;
    state[22] = shared->initial_D_tot;
    state[23] = shared->initial_N_tot;
    state[24] = shared->initial_total_vax;
    std::copy(shared->initial_S.begin(), shared->initial_S.end(), state.begin() + 25);
    std::copy(shared->initial_Ea.begin(), shared->initial_Ea.end(), state.begin() + shared->offset_variable_Ea);
    std::copy(shared->initial_Eb.begin(), shared->initial_Eb.end(), state.begin() + shared->offset_variable_Eb);
    std::copy(shared->initial_Ir.begin(), shared->initial_Ir.end(), state.begin() + shared->offset_variable_Ir);
    std::copy(shared->initial_Id.begin(), shared->initial_Id.end(), state.begin() + shared->offset_variable_Id);
    std::copy(shared->initial_R.begin(), shared->initial_R.end(), state.begin() + shared->offset_variable_R);
    std::copy(shared->initial_D.begin(), shared->initial_D.end(), state.begin() + shared->offset_variable_D);
    std::copy(shared->initial_E.begin(), shared->initial_E.end(), state.begin() + shared->offset_variable_E);
    std::copy(shared->initial_I.begin(), shared->initial_I.end(), state.begin() + shared->offset_variable_I);
    std::copy(shared->initial_N.begin(), shared->initial_N.end(), state.begin() + shared->offset_variable_N);
    return state;
  }
  void update(size_t step, const real_type * state, rng_state_type& rng_state, real_type * state_next) {
    const real_type time = state[0];
    const real_type prioritisation_step = state[1];
    const real_type vax_given_S = state[14];
    const real_type vax_given_Ea = state[15];
    const real_type vax_given_Eb = state[16];
    const real_type vax_given_R = state[17];
    const real_type * S = state + 25;
    const real_type * Ea = state + shared->offset_variable_Ea;
    const real_type * Eb = state + shared->offset_variable_Eb;
    const real_type * Ir = state + shared->offset_variable_Ir;
    const real_type * Id = state + shared->offset_variable_Id;
    const real_type * R = state + shared->offset_variable_R;
    const real_type * D = state + shared->offset_variable_D;
    const real_type * E = state + shared->offset_variable_E;
    const real_type * I = state + shared->offset_variable_I;
    const real_type * N = state + shared->offset_variable_N;
    const real_type cases = state[2];
    const real_type deaths = state[3];
    const real_type total_vax = state[24];
    state_next[0] = (step + 1) * shared->dt;
    state_next[24] = total_vax + vax_given_S + vax_given_Ea + vax_given_Eb + vax_given_R;
    real_type is_same_week = fmodr<real_type>(step, shared->steps_per_week) > 0;
    state_next[22] = odin_sum2<real_type>(D, 0, shared->dim_D_1, 0, shared->dim_D_2, shared->dim_D_1);
    for (int i = 1; i <= shared->dim_E_1; ++i) {
      for (int j = 1; j <= shared->dim_E_2; ++j) {
        state_next[shared->offset_variable_E + i - 1 + shared->dim_E_1 * (j - 1)] = Ea[shared->dim_Ea_1 * (j - 1) + i - 1] + Eb[shared->dim_Eb_1 * (j - 1) + i - 1];
      }
    }
    state_next[19] = odin_sum2<real_type>(E, 0, shared->dim_E_1, 0, shared->dim_E_2, shared->dim_E_1);
    for (int i = 1; i <= shared->dim_I_1; ++i) {
      for (int j = 1; j <= shared->dim_I_2; ++j) {
        state_next[shared->offset_variable_I + i - 1 + shared->dim_I_1 * (j - 1)] = Ir[shared->dim_Ir_1 * (j - 1) + i - 1] + Id[shared->dim_Id_1 * (j - 1) + i - 1];
      }
    }
    state_next[20] = odin_sum2<real_type>(I, 0, shared->dim_I_1, 0, shared->dim_I_2, shared->dim_I_1);
    for (int i = 1; i <= shared->dim_N_1; ++i) {
      for (int j = 1; j <= shared->dim_N_2; ++j) {
        state_next[shared->offset_variable_N + i - 1 + shared->dim_N_1 * (j - 1)] = S[shared->dim_S_1 * (j - 1) + i - 1] + Ea[shared->dim_Ea_1 * (j - 1) + i - 1] + Eb[shared->dim_Eb_1 * (j - 1) + i - 1] + Ir[shared->dim_Ir_1 * (j - 1) + i - 1] + Id[shared->dim_Id_1 * (j - 1) + i - 1] + R[shared->dim_R_1 * (j - 1) + i - 1] + D[shared->dim_D_1 * (j - 1) + i - 1];
      }
    }
    state_next[23] = odin_sum2<real_type>(N, 0, shared->dim_N_1, 0, shared->dim_N_2, shared->dim_N_1);
    state_next[21] = odin_sum2<real_type>(R, 0, shared->dim_R_1, 0, shared->dim_R_2, shared->dim_R_1);
    state_next[18] = odin_sum2<real_type>(S, 0, shared->dim_S_1, 0, shared->dim_S_2, shared->dim_S_1);
    for (int i = 1; i <= shared->dim_daily_doses_t_1; ++i) {
      for (int j = 1; j <= shared->dim_daily_doses_t_2; ++j) {
        internal.daily_doses_t[i - 1 + shared->dim_daily_doses_t_1 * (j - 1)] = (static_cast<int>(time) >= (shared->vaccination_campaign_length) ? shared->daily_doses[shared->dim_daily_doses_1 * (j - 1) + shared->vaccination_campaign_length - 1] : shared->daily_doses[shared->dim_daily_doses_1 * (j - 1) + time - 1]);
      }
    }
    for (int i = 1; i <= shared->dim_I_infectious_1; ++i) {
      for (int j = 1; j <= shared->dim_I_infectious_2; ++j) {
        internal.I_infectious[i - 1 + shared->dim_I_infectious_1 * (j - 1)] = I[shared->dim_I_1 * (j - 1) + i - 1] * (1 - shared->ve_T[j - 1]);
      }
    }
    for (int i = 1; i <= shared->dim_n_eligible; ++i) {
      internal.n_eligible[i - 1] = (S[shared->dim_S_1 * 0 + i - 1] + Ea[shared->dim_Ea_1 * 0 + i - 1] + Eb[shared->dim_Eb_1 * 0 + i - 1] + R[shared->dim_R_1 * 0 + i - 1]) * shared->prioritisation_strategy[shared->dim_prioritisation_strategy_1 * (prioritisation_step - 1) + i - 1];
    }
    for (int i = 1; i <= shared->dim_n_IdD_1; ++i) {
      for (int j = 1; j <= shared->dim_n_IdD_2; ++j) {
        internal.n_IdD[i - 1 + shared->dim_n_IdD_1 * (j - 1)] = dust::random::binomial<real_type>(rng_state, Id[shared->dim_Id_1 * (j - 1) + i - 1], shared->p_IdD);
      }
    }
    for (int i = 1; i <= shared->dim_n_IrR_1; ++i) {
      for (int j = 1; j <= shared->dim_n_IrR_2; ++j) {
        internal.n_IrR[i - 1 + shared->dim_n_IrR_1 * (j - 1)] = dust::random::binomial<real_type>(rng_state, Ir[shared->dim_Ir_1 * (j - 1) + i - 1], shared->p_IrR);
      }
    }
    for (int i = 1; i <= shared->dim_total_vaccinated_t_1; ++i) {
      for (int j = 1; j <= shared->dim_total_vaccinated_t_2; ++j) {
        internal.total_vaccinated_t[i - 1 + shared->dim_total_vaccinated_t_1 * (j - 1)] = odin_sum2<real_type>(N, i - 1, i, j - 1, j, shared->dim_N_1) - N[shared->dim_N_1 * 0 + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_delta_D_1; ++i) {
      for (int j = 1; j <= shared->dim_delta_D_2; ++j) {
        internal.delta_D[i - 1 + shared->dim_delta_D_1 * (j - 1)] = internal.n_IdD[shared->dim_n_IdD_1 * (j - 1) + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_delta_R_1; ++i) {
      for (int j = 1; j <= shared->dim_delta_R_2; ++j) {
        internal.delta_R[i - 1 + shared->dim_delta_R_1 * (j - 1)] = internal.n_IrR[shared->dim_n_IrR_1 * (j - 1) + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_n_vaccination_t_Ea_1; ++i) {
      for (int j = 1; j <= shared->dim_n_vaccination_t_Ea_2; ++j) {
        internal.n_vaccination_t_Ea[i - 1 + shared->dim_n_vaccination_t_Ea_1 * (j - 1)] = 0;
      }
    }
    for (int i = 1; i <= shared->dim_n_vaccination_t_Ea_1; ++i) {
      int j = 1;
      internal.n_vaccination_t_Ea[i - 1 + shared->dim_n_vaccination_t_Ea_1 * (j - 1)] = dust::math::min(dust::math::floor((internal.daily_doses_t[shared->dim_daily_doses_t_1 * (j - 1) + 0] * Ea[shared->dim_Ea_1 * 0 + i - 1] * shared->prioritisation_strategy[shared->dim_prioritisation_strategy_1 * (prioritisation_step - 1) + i - 1] * shared->vaccine_uptake[i - 1]) / (real_type) odin_sum1<real_type>(internal.n_eligible.data(), 0, shared->dim_n_eligible)), Ea[shared->dim_Ea_1 * 0 + i - 1]);
    }
    for (int i = 1; i <= shared->dim_n_vaccination_t_Eb_1; ++i) {
      for (int j = 1; j <= shared->dim_n_vaccination_t_Eb_2; ++j) {
        internal.n_vaccination_t_Eb[i - 1 + shared->dim_n_vaccination_t_Eb_1 * (j - 1)] = 0;
      }
    }
    for (int i = 1; i <= shared->dim_n_vaccination_t_Eb_1; ++i) {
      int j = 1;
      internal.n_vaccination_t_Eb[i - 1 + shared->dim_n_vaccination_t_Eb_1 * (j - 1)] = dust::math::min(dust::math::floor((internal.daily_doses_t[shared->dim_daily_doses_t_1 * (j - 1) + 0] * Eb[shared->dim_Eb_1 * 0 + i - 1] * shared->prioritisation_strategy[shared->dim_prioritisation_strategy_1 * (prioritisation_step - 1) + i - 1] * shared->vaccine_uptake[i - 1]) / (real_type) odin_sum1<real_type>(internal.n_eligible.data(), 0, shared->dim_n_eligible)), Eb[shared->dim_Eb_1 * 0 + i - 1]);
    }
    for (int i = 1; i <= shared->dim_n_vaccination_t_R_1; ++i) {
      for (int j = 1; j <= shared->dim_n_vaccination_t_R_2; ++j) {
        internal.n_vaccination_t_R[i - 1 + shared->dim_n_vaccination_t_R_1 * (j - 1)] = 0;
      }
    }
    for (int i = 1; i <= shared->dim_n_vaccination_t_R_1; ++i) {
      int j = 1;
      internal.n_vaccination_t_R[i - 1 + shared->dim_n_vaccination_t_R_1 * (j - 1)] = dust::math::min(dust::math::floor((internal.daily_doses_t[shared->dim_daily_doses_t_1 * (j - 1) + 0] * R[shared->dim_R_1 * 0 + i - 1] * shared->prioritisation_strategy[shared->dim_prioritisation_strategy_1 * (prioritisation_step - 1) + i - 1] * shared->vaccine_uptake[i - 1]) / (real_type) odin_sum1<real_type>(internal.n_eligible.data(), 0, shared->dim_n_eligible)), R[shared->dim_R_1 * 0 + i - 1]);
    }
    for (int i = 1; i <= shared->dim_n_vaccination_t_S_1; ++i) {
      for (int j = 1; j <= shared->dim_n_vaccination_t_S_2; ++j) {
        internal.n_vaccination_t_S[i - 1 + shared->dim_n_vaccination_t_S_1 * (j - 1)] = 0;
      }
    }
    for (int i = 1; i <= shared->dim_n_vaccination_t_S_1; ++i) {
      int j = 1;
      internal.n_vaccination_t_S[i - 1 + shared->dim_n_vaccination_t_S_1 * (j - 1)] = dust::math::min(dust::math::floor((internal.daily_doses_t[shared->dim_daily_doses_t_1 * (j - 1) + 0] * S[shared->dim_S_1 * 0 + i - 1] * shared->prioritisation_strategy[shared->dim_prioritisation_strategy_1 * (prioritisation_step - 1) + i - 1] * shared->vaccine_uptake[i - 1]) / (real_type) odin_sum1<real_type>(internal.n_eligible.data(), 0, shared->dim_n_eligible)), S[shared->dim_S_1 * 0 + i - 1]);
    }
    for (int i = 1; i <= shared->dim_prop_infectious; ++i) {
      internal.prop_infectious[i - 1] = odin_sum2<real_type>(internal.I_infectious.data(), i - 1, i, 0, shared->dim_I_infectious_2, shared->dim_I_infectious_1) / (real_type) odin_sum2<real_type>(N, i - 1, i, 0, shared->dim_N_2, shared->dim_N_1);
    }
    for (int i = 1; i <= shared->dim_target_met_t_1; ++i) {
      for (int j = 1; j <= shared->dim_target_met_t_2; ++j) {
        internal.target_met_t[i - 1 + shared->dim_target_met_t_1 * (j - 1)] = (internal.total_vaccinated_t[shared->dim_total_vaccinated_t_1 * 0 + i - 1] > shared->vaccination_coverage_target[shared->dim_vaccination_coverage_target_1 * (prioritisation_step - 1) + i - 1] ? 1 : 0);
      }
    }
    state_next[3] = deaths * is_same_week + odin_sum2<real_type>(internal.n_IdD.data(), 0, shared->dim_n_IdD_1, 0, shared->dim_n_IdD_2, shared->dim_n_IdD_1);
    state_next[9] = cases * is_same_week + odin_sum2<real_type>(internal.n_IdD.data(), 0, 1, 0, shared->dim_n_IdD_2, shared->dim_n_IdD_1);
    state_next[11] = cases * is_same_week + odin_sum2<real_type>(internal.n_IdD.data(), 3, 16, 0, shared->dim_n_IdD_2, shared->dim_n_IdD_1);
    state_next[10] = cases * is_same_week + odin_sum2<real_type>(internal.n_IdD.data(), 1, 3, 0, shared->dim_n_IdD_2, shared->dim_n_IdD_1);
    state_next[12] = cases * is_same_week + odin_sum2<real_type>(internal.n_IdD.data(), 16, 17, 0, shared->dim_n_IdD_2, shared->dim_n_IdD_1);
    state_next[13] = cases * is_same_week + odin_sum2<real_type>(internal.n_IdD.data(), 17, 18, 0, shared->dim_n_IdD_2, shared->dim_n_IdD_1);
    for (int i = 1; i <= shared->dim_delta_Ea_n_vaccination_1; ++i) {
      for (int j = 1; j <= shared->dim_delta_Ea_n_vaccination_2; ++j) {
        internal.delta_Ea_n_vaccination[i - 1 + shared->dim_delta_Ea_n_vaccination_1 * (j - 1)] = (j == 1 ? (- internal.n_vaccination_t_Ea[shared->dim_n_vaccination_t_Ea_1 * (j - 1) + i - 1]) : (j == shared->n_vax ? (internal.n_vaccination_t_Ea[shared->dim_n_vaccination_t_Ea_1 * (j - 1 - 1) + i - 1]) : (- internal.n_vaccination_t_Ea[shared->dim_n_vaccination_t_Ea_1 * (j - 1) + i - 1] + internal.n_vaccination_t_Ea[shared->dim_n_vaccination_t_Ea_1 * (j - 1 - 1) + i - 1])));
      }
    }
    for (int i = 1; i <= shared->dim_delta_Eb_n_vaccination_1; ++i) {
      for (int j = 1; j <= shared->dim_delta_Eb_n_vaccination_2; ++j) {
        internal.delta_Eb_n_vaccination[i - 1 + shared->dim_delta_Eb_n_vaccination_1 * (j - 1)] = (j == 1 ? (- internal.n_vaccination_t_Eb[shared->dim_n_vaccination_t_Eb_1 * (j - 1) + i - 1]) : (j == shared->n_vax ? (internal.n_vaccination_t_Eb[shared->dim_n_vaccination_t_Eb_1 * (j - 1 - 1) + i - 1]) : (- internal.n_vaccination_t_Eb[shared->dim_n_vaccination_t_Eb_1 * (j - 1) + i - 1] + internal.n_vaccination_t_Eb[shared->dim_n_vaccination_t_Eb_1 * (j - 1 - 1) + i - 1])));
      }
    }
    for (int i = 1; i <= shared->dim_delta_R_n_vaccination_1; ++i) {
      for (int j = 1; j <= shared->dim_delta_R_n_vaccination_2; ++j) {
        internal.delta_R_n_vaccination[i - 1 + shared->dim_delta_R_n_vaccination_1 * (j - 1)] = (j == 1 ? (- internal.n_vaccination_t_R[shared->dim_n_vaccination_t_R_1 * (j - 1) + i - 1]) : (j == shared->n_vax ? (internal.n_vaccination_t_R[shared->dim_n_vaccination_t_R_1 * (j - 1 - 1) + i - 1]) : (- internal.n_vaccination_t_R[shared->dim_n_vaccination_t_R_1 * (j - 1) + i - 1] + internal.n_vaccination_t_R[shared->dim_n_vaccination_t_R_1 * (j - 1 - 1) + i - 1])));
      }
    }
    for (int i = 1; i <= shared->dim_delta_S_n_vaccination_1; ++i) {
      for (int j = 1; j <= shared->dim_delta_S_n_vaccination_2; ++j) {
        internal.delta_S_n_vaccination[i - 1 + shared->dim_delta_S_n_vaccination_1 * (j - 1)] = (j == 1 ? (- internal.n_vaccination_t_S[shared->dim_n_vaccination_t_S_1 * (j - 1) + i - 1]) : (j == shared->n_vax ? (internal.n_vaccination_t_S[shared->dim_n_vaccination_t_S_1 * (j - 1 - 1) + i - 1]) : (- internal.n_vaccination_t_S[shared->dim_n_vaccination_t_S_1 * (j - 1) + i - 1] + internal.n_vaccination_t_S[shared->dim_n_vaccination_t_S_1 * (j - 1 - 1) + i - 1])));
      }
    }
    for (int i = 1; i <= shared->dim_s_ij_1; ++i) {
      for (int j = 1; j <= shared->dim_s_ij_2; ++j) {
        internal.s_ij[i - 1 + shared->dim_s_ij_1 * (j - 1)] = shared->m[shared->dim_m_1 * (j - 1) + i - 1] * internal.prop_infectious[j - 1];
      }
    }
    for (int i = 1; i <= shared->dim_D_1; ++i) {
      for (int j = 1; j <= shared->dim_D_2; ++j) {
        state_next[shared->offset_variable_D + i - 1 + shared->dim_D_1 * (j - 1)] = D[shared->dim_D_1 * (j - 1) + i - 1] + internal.delta_D[shared->dim_delta_D_1 * (j - 1) + i - 1];
      }
    }
    state_next[1] = (odin_sum2<real_type>(internal.target_met_t.data(), 0, shared->dim_target_met_t_1, 0, shared->dim_target_met_t_2, shared->dim_target_met_t_1) == shared->n_group ? prioritisation_step + 1 : prioritisation_step);
    state_next[15] = odin_sum2<real_type>(internal.n_vaccination_t_Ea.data(), 0, shared->dim_n_vaccination_t_Ea_1, 0, shared->dim_n_vaccination_t_Ea_2, shared->dim_n_vaccination_t_Ea_1);
    state_next[16] = odin_sum2<real_type>(internal.n_vaccination_t_Eb.data(), 0, shared->dim_n_vaccination_t_Eb_1, 0, shared->dim_n_vaccination_t_Eb_2, shared->dim_n_vaccination_t_Eb_1);
    state_next[17] = odin_sum2<real_type>(internal.n_vaccination_t_R.data(), 0, shared->dim_n_vaccination_t_R_1, 0, shared->dim_n_vaccination_t_R_2, shared->dim_n_vaccination_t_R_1);
    state_next[14] = odin_sum2<real_type>(internal.n_vaccination_t_S.data(), 0, shared->dim_n_vaccination_t_S_1, 0, shared->dim_n_vaccination_t_S_2, shared->dim_n_vaccination_t_S_1);
    for (int i = 1; i <= shared->dim_lambda_1; ++i) {
      for (int j = 1; j <= shared->dim_lambda_2; ++j) {
        internal.lambda[i - 1 + shared->dim_lambda_1 * (j - 1)] = ((shared->beta_h * odin_sum2<real_type>(internal.s_ij.data(), i - 1, i, 0, shared->dim_s_ij_2, shared->dim_s_ij_1)) + shared->beta_z[i - 1]) * (1 - shared->ve_I[j - 1]);
      }
    }
    for (int i = 1; i <= shared->dim_n_EaEb_1; ++i) {
      for (int j = 1; j <= shared->dim_n_EaEb_2; ++j) {
        internal.n_EaEb[i - 1 + shared->dim_n_EaEb_1 * (j - 1)] = dust::random::binomial<real_type>(rng_state, Ea[shared->dim_Ea_1 * (j - 1) + i - 1] + internal.delta_Ea_n_vaccination[shared->dim_delta_Ea_n_vaccination_1 * (j - 1) + i - 1], shared->p_EE);
      }
    }
    for (int i = 1; i <= shared->dim_n_EbI_1; ++i) {
      for (int j = 1; j <= shared->dim_n_EbI_2; ++j) {
        internal.n_EbI[i - 1 + shared->dim_n_EbI_1 * (j - 1)] = dust::random::binomial<real_type>(rng_state, Eb[shared->dim_Eb_1 * (j - 1) + i - 1] + internal.delta_Eb_n_vaccination[shared->dim_delta_Eb_n_vaccination_1 * (j - 1) + i - 1], shared->p_EI);
      }
    }
    for (int i = 1; i <= shared->dim_R_1; ++i) {
      for (int j = 1; j <= shared->dim_R_2; ++j) {
        state_next[shared->offset_variable_R + i - 1 + shared->dim_R_1 * (j - 1)] = R[shared->dim_R_1 * (j - 1) + i - 1] + internal.delta_R_n_vaccination[shared->dim_delta_R_n_vaccination_1 * (j - 1) + i - 1] + internal.delta_R[shared->dim_delta_R_1 * (j - 1) + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_delta_Eb_1; ++i) {
      for (int j = 1; j <= shared->dim_delta_Eb_2; ++j) {
        internal.delta_Eb[i - 1 + shared->dim_delta_Eb_1 * (j - 1)] = internal.n_EaEb[shared->dim_n_EaEb_1 * (j - 1) + i - 1] - internal.n_EbI[shared->dim_n_EbI_1 * (j - 1) + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_n_EbId_1; ++i) {
      for (int j = 1; j <= shared->dim_n_EbId_2; ++j) {
        internal.n_EbId[i - 1 + shared->dim_n_EbId_1 * (j - 1)] = dust::random::binomial<real_type>(rng_state, internal.n_EbI[shared->dim_n_EbI_1 * (j - 1) + i - 1], shared->CFR[shared->dim_CFR_1 * (j - 1) + i - 1]);
      }
    }
    for (int i = 1; i <= shared->dim_p_SE_1; ++i) {
      for (int j = 1; j <= shared->dim_p_SE_2; ++j) {
        internal.p_SE[i - 1 + shared->dim_p_SE_1 * (j - 1)] = 1 - dust::math::exp(- internal.lambda[shared->dim_lambda_1 * (j - 1) + i - 1] * shared->dt);
      }
    }
    for (int i = 1; i <= shared->dim_delta_Id_1; ++i) {
      for (int j = 1; j <= shared->dim_delta_Id_2; ++j) {
        internal.delta_Id[i - 1 + shared->dim_delta_Id_1 * (j - 1)] = internal.n_EbId[shared->dim_n_EbId_1 * (j - 1) + i - 1] - internal.n_IdD[shared->dim_n_IdD_1 * (j - 1) + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_n_EbIr_1; ++i) {
      for (int j = 1; j <= shared->dim_n_EbIr_2; ++j) {
        internal.n_EbIr[i - 1 + shared->dim_n_EbIr_1 * (j - 1)] = internal.n_EbI[shared->dim_n_EbI_1 * (j - 1) + i - 1] - internal.n_EbId[shared->dim_n_EbId_1 * (j - 1) + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_n_SEa_1; ++i) {
      for (int j = 1; j <= shared->dim_n_SEa_2; ++j) {
        internal.n_SEa[i - 1 + shared->dim_n_SEa_1 * (j - 1)] = dust::random::binomial<real_type>(rng_state, S[shared->dim_S_1 * (j - 1) + i - 1] + internal.delta_S_n_vaccination[shared->dim_delta_S_n_vaccination_1 * (j - 1) + i - 1], internal.p_SE[shared->dim_p_SE_1 * (j - 1) + i - 1]);
      }
    }
    for (int i = 1; i <= shared->dim_Eb_1; ++i) {
      for (int j = 1; j <= shared->dim_Eb_2; ++j) {
        state_next[shared->offset_variable_Eb + i - 1 + shared->dim_Eb_1 * (j - 1)] = Eb[shared->dim_Eb_1 * (j - 1) + i - 1] + internal.delta_Eb_n_vaccination[shared->dim_delta_Eb_n_vaccination_1 * (j - 1) + i - 1] + internal.delta_Eb[shared->dim_delta_Eb_1 * (j - 1) + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_delta_Ea_1; ++i) {
      for (int j = 1; j <= shared->dim_delta_Ea_2; ++j) {
        internal.delta_Ea[i - 1 + shared->dim_delta_Ea_1 * (j - 1)] = internal.n_SEa[shared->dim_n_SEa_1 * (j - 1) + i - 1] - internal.n_EaEb[shared->dim_n_EaEb_1 * (j - 1) + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_delta_Ir_1; ++i) {
      for (int j = 1; j <= shared->dim_delta_Ir_2; ++j) {
        internal.delta_Ir[i - 1 + shared->dim_delta_Ir_1 * (j - 1)] = internal.n_EbIr[shared->dim_n_EbIr_1 * (j - 1) + i - 1] - internal.n_IrR[shared->dim_n_IrR_1 * (j - 1) + i - 1];
      }
    }
    state_next[2] = cases * is_same_week + odin_sum2<real_type>(internal.n_SEa.data(), 0, shared->dim_n_SEa_1, 0, shared->dim_n_SEa_2, shared->dim_n_SEa_1);
    state_next[4] = cases * is_same_week + odin_sum2<real_type>(internal.n_SEa.data(), 0, 1, 0, shared->dim_n_SEa_2, shared->dim_n_SEa_1);
    state_next[6] = cases * is_same_week + odin_sum2<real_type>(internal.n_SEa.data(), 3, 16, 0, shared->dim_n_SEa_2, shared->dim_n_SEa_1);
    state_next[5] = cases * is_same_week + odin_sum2<real_type>(internal.n_SEa.data(), 1, 3, 0, shared->dim_n_SEa_2, shared->dim_n_SEa_1);
    state_next[7] = cases * is_same_week + odin_sum2<real_type>(internal.n_SEa.data(), 16, 17, 0, shared->dim_n_SEa_2, shared->dim_n_SEa_1);
    state_next[8] = cases * is_same_week + odin_sum2<real_type>(internal.n_SEa.data(), 17, 18, 0, shared->dim_n_SEa_2, shared->dim_n_SEa_1);
    for (int i = 1; i <= shared->dim_Id_1; ++i) {
      for (int j = 1; j <= shared->dim_Id_2; ++j) {
        state_next[shared->offset_variable_Id + i - 1 + shared->dim_Id_1 * (j - 1)] = Id[shared->dim_Id_1 * (j - 1) + i - 1] + internal.delta_Id[shared->dim_delta_Id_1 * (j - 1) + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_S_1; ++i) {
      for (int j = 1; j <= shared->dim_S_2; ++j) {
        state_next[25 + i - 1 + shared->dim_S_1 * (j - 1)] = S[shared->dim_S_1 * (j - 1) + i - 1] + internal.delta_S_n_vaccination[shared->dim_delta_S_n_vaccination_1 * (j - 1) + i - 1] - internal.n_SEa[shared->dim_n_SEa_1 * (j - 1) + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_Ea_1; ++i) {
      for (int j = 1; j <= shared->dim_Ea_2; ++j) {
        state_next[shared->offset_variable_Ea + i - 1 + shared->dim_Ea_1 * (j - 1)] = Ea[shared->dim_Ea_1 * (j - 1) + i - 1] + internal.delta_Ea_n_vaccination[shared->dim_delta_Ea_n_vaccination_1 * (j - 1) + i - 1] + internal.delta_Ea[shared->dim_delta_Ea_1 * (j - 1) + i - 1];
      }
    }
    for (int i = 1; i <= shared->dim_Ir_1; ++i) {
      for (int j = 1; j <= shared->dim_Ir_2; ++j) {
        state_next[shared->offset_variable_Ir + i - 1 + shared->dim_Ir_1 * (j - 1)] = Ir[shared->dim_Ir_1 * (j - 1) + i - 1] + internal.delta_Ir[shared->dim_delta_Ir_1 * (j - 1) + i - 1];
      }
    }
  }
private:
  std::shared_ptr<const shared_type> shared;
  internal_type internal;
};
template <typename real_type, typename container>
__host__ __device__ real_type odin_sum2(const container x, int from_i, int to_i, int from_j, int to_j, int dim_x_1) {
  real_type tot = 0.0;
  for (int j = from_j; j < to_j; ++j) {
    int jj = j * dim_x_1;
    for (int i = from_i; i < to_i; ++i) {
      tot += x[i + jj];
    }
  }
  return tot;
}
#include <array>
#include <cpp11/R.hpp>
#include <cpp11/sexp.hpp>
#include <cpp11/doubles.hpp>
#include <cpp11/integers.hpp>
#include <cpp11/list.hpp>
#include <cpp11/strings.hpp>
#include <memory>
#include <vector>

template <typename T>
inline bool is_na(T x);

template <>
inline bool is_na(int x) {
  return x == NA_INTEGER;
}

template <>
inline bool is_na(double x) {
  return ISNA(x);
}

inline size_t object_length(cpp11::sexp x) {
  return ::Rf_xlength(x);
}

template <typename T>
void user_check_value(T value, const char *name, T min, T max) {
  if (is_na(value)) {
    cpp11::stop("'%s' must not be NA", name);
  }
  if (!is_na(min) && value < min) {
    cpp11::stop("Expected '%s' to be at least %g", name, (double) min);
  }
  if (!is_na(max) && value > max) {
    cpp11::stop("Expected '%s' to be at most %g", name, (double) max);
  }
}

template <typename T>
void user_check_array_value(const std::vector<T>& value, const char *name,
                            T min, T max) {
  for (auto& x : value) {
    user_check_value(x, name, min, max);
  }
}

inline size_t user_get_array_rank(cpp11::sexp x) {
  if (!::Rf_isArray(x)) {
    return 1;
  } else {
    cpp11::integers dim = cpp11::as_cpp<cpp11::integers>(x.attr("dim"));
    return dim.size();
  }
}

template <size_t N>
void user_check_array_rank(cpp11::sexp x, const char *name) {
  size_t rank = user_get_array_rank(x);
  if (rank != N) {
    if (N == 1) {
      cpp11::stop("Expected a vector for '%s'", name);
    } else if (N == 2) {
      cpp11::stop("Expected a matrix for '%s'", name);
    } else {
      cpp11::stop("Expected an array of rank %d for '%s'", N, name);
    }
  }
}

template <size_t N>
void user_check_array_dim(cpp11::sexp x, const char *name,
                          const std::array<int, N>& dim_expected) {
  cpp11::integers dim = cpp11::as_cpp<cpp11::integers>(x.attr("dim"));
  for (size_t i = 0; i < N; ++i) {
    if (dim[(int)i] != dim_expected[i]) {
      Rf_error("Incorrect size of dimension %zu of '%s' (expected %d)",
               i + 1, name, dim_expected[i]);
    }
  }
}

template <>
inline void user_check_array_dim<1>(cpp11::sexp x, const char *name,
                                    const std::array<int, 1>& dim_expected) {
  if ((int)object_length(x) != dim_expected[0]) {
    cpp11::stop("Expected length %d value for '%s'", dim_expected[0], name);
  }
}

template <size_t N>
void user_set_array_dim(cpp11::sexp x, const char *name,
                        std::array<int, N>& dim) {
  cpp11::integers dim_given = cpp11::as_cpp<cpp11::integers>(x.attr("dim"));
  std::copy(dim_given.begin(), dim_given.end(), dim.begin());
}

template <>
inline void user_set_array_dim<1>(cpp11::sexp x, const char *name,
                                  std::array<int, 1>& dim) {
  dim[0] = object_length(x);
}

template <typename T>
T user_get_scalar(cpp11::list user, const char *name,
                  const T previous, T min, T max) {
  T ret = previous;
  cpp11::sexp x = user[name];
  if (x != R_NilValue) {
    if (object_length(x) != 1) {
      cpp11::stop("Expected a scalar numeric for '%s'", name);
    }
    // TODO: when we're getting out an integer this is a bit too relaxed
    if (TYPEOF(x) == REALSXP) {
      ret = cpp11::as_cpp<T>(x);
    } else if (TYPEOF(x) == INTSXP) {
      ret = cpp11::as_cpp<T>(x);
    } else {
      cpp11::stop("Expected a numeric value for %s", name);
    }
  }

  if (is_na(ret)) {
    cpp11::stop("Expected a value for '%s'", name);
  }
  user_check_value<T>(ret, name, min, max);
  return ret;
}

template <>
inline float user_get_scalar<float>(cpp11::list user, const char *name,
                                    const float previous, float min, float max) {
  double value = user_get_scalar<double>(user, name, previous, min, max);
  return static_cast<float>(value);
}

template <typename T>
std::vector<T> user_get_array_value(cpp11::sexp x, const char * name,
                                    T min, T max) {
  std::vector<T> ret = cpp11::as_cpp<std::vector<T>>(x);
  user_check_array_value<T>(ret, name, min, max);
  return ret;
}

template <typename T, size_t N>
std::vector<T> user_get_array_fixed(cpp11::list user, const char *name,
                                    const std::vector<T> previous,
                                    const std::array<int, N>& dim,
                                    T min, T max) {
  cpp11::sexp x = user[name];
  if (x == R_NilValue) {
    if (previous.size() == 0) {
      cpp11::stop("Expected a value for '%s'", name);
    }
    return previous;
  }

  user_check_array_rank<N>(x, name);
  user_check_array_dim<N>(x, name, dim);

  return user_get_array_value<T>(x, name, min, max);
}

template <typename T, size_t N>
std::vector<T> user_get_array_variable(cpp11::list user, const char *name,
                                       std::vector<T> previous,
                                       std::array<int, N>& dim,
                                       T min, T max) {
  cpp11::sexp x = user[name];
  if (x == R_NilValue) {
    if (previous.size() == 0) {
      cpp11::stop("Expected a value for '%s'", name);
    }
    return previous;
  }

  user_check_array_rank<N>(x, name);
  user_set_array_dim<N>(x, name, dim);

  return user_get_array_value<T>(x, name, min, max);
}

template <>
inline std::vector<float> user_get_array_value(cpp11::sexp x, const char * name,
                                               float min, float max) {
  // NOTE: possible under/overflow here for min/max because we've
  // downcast this.
  std::vector<double> value = user_get_array_value<double>(x, name, min, max);
  std::vector<float> ret(value.size());
  std::copy(value.begin(), value.end(), ret.begin());
  return ret;
}

// This is sum with inclusive "from", exclusive "to", following the
// same function in odin
template <typename real_type, typename container>
__host__ __device__
real_type odin_sum1(const container x, size_t from, size_t to) {
  real_type tot = 0.0;
  for (size_t i = from; i < to; ++i) {
    tot += x[i];
  }
  return tot;
}

inline cpp11::writable::integers integer_sequence(size_t from, size_t len) {
  cpp11::writable::integers ret(len);
  int* data = INTEGER(ret);
  for (size_t i = 0, j = from; i < len; ++i, ++j) {
    data[i] = j;
  }
  return ret;
}
namespace dust {
template<>
dust::pars_type<model_targeted_vax> dust_pars<model_targeted_vax>(cpp11::list user) {
  using real_type = typename model_targeted_vax::real_type;
  auto shared = std::make_shared<model_targeted_vax::shared_type>();
  model_targeted_vax::internal_type internal;
  shared->initial_cases = 0;
  shared->initial_cases_0_5 = 0;
  shared->initial_cases_15_plus = 0;
  shared->initial_cases_5_15 = 0;
  shared->initial_cases_PBS = 0;
  shared->initial_cases_SW = 0;
  shared->initial_deaths = 0;
  shared->initial_deaths_0_5 = 0;
  shared->initial_deaths_15_plus = 0;
  shared->initial_deaths_5_15 = 0;
  shared->initial_deaths_PBS = 0;
  shared->initial_deaths_SW = 0;
  shared->initial_prioritisation_step = 1;
  shared->initial_total_vax = 0;
  shared->initial_vax_given_Ea = 0;
  shared->initial_vax_given_Eb = 0;
  shared->initial_vax_given_R = 0;
  shared->initial_vax_given_S = 0;
  shared->beta_h = NA_REAL;
  shared->gamma_E = NA_REAL;
  shared->gamma_Id = NA_REAL;
  shared->gamma_Ir = NA_REAL;
  shared->n_group = NA_INTEGER;
  shared->N_prioritisation_steps = NA_INTEGER;
  shared->n_vax = NA_INTEGER;
  shared->vaccination_campaign_length = NA_INTEGER;
  shared->dt = 1;
  internal.initial_time = 0;
  shared->beta_h = user_get_scalar<real_type>(user, "beta_h", shared->beta_h, NA_REAL, NA_REAL);
  shared->dt = user_get_scalar<real_type>(user, "dt", shared->dt, NA_REAL, NA_REAL);
  shared->gamma_E = user_get_scalar<real_type>(user, "gamma_E", shared->gamma_E, NA_REAL, NA_REAL);
  shared->gamma_Id = user_get_scalar<real_type>(user, "gamma_Id", shared->gamma_Id, NA_REAL, NA_REAL);
  shared->gamma_Ir = user_get_scalar<real_type>(user, "gamma_Ir", shared->gamma_Ir, NA_REAL, NA_REAL);
  shared->n_group = user_get_scalar<int>(user, "n_group", shared->n_group, NA_INTEGER, NA_INTEGER);
  shared->N_prioritisation_steps = user_get_scalar<int>(user, "N_prioritisation_steps", shared->N_prioritisation_steps, NA_INTEGER, NA_INTEGER);
  shared->n_vax = user_get_scalar<int>(user, "n_vax", shared->n_vax, NA_INTEGER, NA_INTEGER);
  shared->vaccination_campaign_length = user_get_scalar<int>(user, "vaccination_campaign_length", shared->vaccination_campaign_length, NA_INTEGER, NA_INTEGER);
  shared->dim_beta_z = shared->n_group;
  shared->dim_CFR_1 = shared->n_group;
  shared->dim_CFR_2 = shared->n_vax;
  shared->dim_D_1 = shared->n_group;
  shared->dim_D_2 = shared->n_vax;
  shared->dim_D0_1 = shared->n_group;
  shared->dim_D0_2 = shared->n_vax;
  shared->dim_daily_doses_1 = shared->vaccination_campaign_length;
  shared->dim_daily_doses_2 = shared->n_vax;
  shared->dim_daily_doses_t_1 = 1;
  shared->dim_daily_doses_t_2 = shared->n_vax;
  shared->dim_delta_D_1 = shared->n_group;
  shared->dim_delta_D_2 = shared->n_vax;
  shared->dim_delta_Ea_1 = shared->n_group;
  shared->dim_delta_Ea_2 = shared->n_vax;
  shared->dim_delta_Ea_n_vaccination_1 = shared->n_group;
  shared->dim_delta_Ea_n_vaccination_2 = shared->n_vax;
  shared->dim_delta_Eb_1 = shared->n_group;
  shared->dim_delta_Eb_2 = shared->n_vax;
  shared->dim_delta_Eb_n_vaccination_1 = shared->n_group;
  shared->dim_delta_Eb_n_vaccination_2 = shared->n_vax;
  shared->dim_delta_Id_1 = shared->n_group;
  shared->dim_delta_Id_2 = shared->n_vax;
  shared->dim_delta_Ir_1 = shared->n_group;
  shared->dim_delta_Ir_2 = shared->n_vax;
  shared->dim_delta_R_1 = shared->n_group;
  shared->dim_delta_R_2 = shared->n_vax;
  shared->dim_delta_R_n_vaccination_1 = shared->n_group;
  shared->dim_delta_R_n_vaccination_2 = shared->n_vax;
  shared->dim_delta_S_n_vaccination_1 = shared->n_group;
  shared->dim_delta_S_n_vaccination_2 = shared->n_vax;
  shared->dim_E_1 = shared->n_group;
  shared->dim_E_2 = shared->n_vax;
  shared->dim_Ea_1 = shared->n_group;
  shared->dim_Ea_2 = shared->n_vax;
  shared->dim_Ea0_1 = shared->n_group;
  shared->dim_Ea0_2 = shared->n_vax;
  shared->dim_Eb_1 = shared->n_group;
  shared->dim_Eb_2 = shared->n_vax;
  shared->dim_Eb0_1 = shared->n_group;
  shared->dim_Eb0_2 = shared->n_vax;
  shared->dim_I_1 = shared->n_group;
  shared->dim_I_2 = shared->n_vax;
  shared->dim_I_infectious_1 = shared->n_group;
  shared->dim_I_infectious_2 = shared->n_vax;
  shared->dim_Id_1 = shared->n_group;
  shared->dim_Id_2 = shared->n_vax;
  shared->dim_Id0_1 = shared->n_group;
  shared->dim_Id0_2 = shared->n_vax;
  shared->dim_Ir_1 = shared->n_group;
  shared->dim_Ir_2 = shared->n_vax;
  shared->dim_Ir0_1 = shared->n_group;
  shared->dim_Ir0_2 = shared->n_vax;
  shared->dim_lambda_1 = shared->n_group;
  shared->dim_lambda_2 = shared->n_vax;
  shared->dim_m_1 = shared->n_group;
  shared->dim_m_2 = shared->n_group;
  shared->dim_N_1 = shared->n_group;
  shared->dim_N_2 = shared->n_vax;
  shared->dim_n_EaEb_1 = shared->n_group;
  shared->dim_n_EaEb_2 = shared->n_vax;
  shared->dim_n_EbI_1 = shared->n_group;
  shared->dim_n_EbI_2 = shared->n_vax;
  shared->dim_n_EbId_1 = shared->n_group;
  shared->dim_n_EbId_2 = shared->n_vax;
  shared->dim_n_EbIr_1 = shared->n_group;
  shared->dim_n_EbIr_2 = shared->n_vax;
  shared->dim_n_eligible = shared->n_group;
  shared->dim_n_IdD_1 = shared->n_group;
  shared->dim_n_IdD_2 = shared->n_vax;
  shared->dim_n_IrR_1 = shared->n_group;
  shared->dim_n_IrR_2 = shared->n_vax;
  shared->dim_n_SEa_1 = shared->n_group;
  shared->dim_n_SEa_2 = shared->n_vax;
  shared->dim_n_vaccination_t_Ea_1 = shared->n_group;
  shared->dim_n_vaccination_t_Ea_2 = shared->n_vax;
  shared->dim_n_vaccination_t_Eb_1 = shared->n_group;
  shared->dim_n_vaccination_t_Eb_2 = shared->n_vax;
  shared->dim_n_vaccination_t_R_1 = shared->n_group;
  shared->dim_n_vaccination_t_R_2 = shared->n_vax;
  shared->dim_n_vaccination_t_S_1 = shared->n_group;
  shared->dim_n_vaccination_t_S_2 = shared->n_vax;
  shared->dim_p_SE_1 = shared->n_group;
  shared->dim_p_SE_2 = shared->n_vax;
  shared->dim_prioritisation_strategy_1 = shared->n_group;
  shared->dim_prioritisation_strategy_2 = shared->N_prioritisation_steps;
  shared->dim_prop_infectious = shared->n_group;
  shared->dim_R_1 = shared->n_group;
  shared->dim_R_2 = shared->n_vax;
  shared->dim_R0_1 = shared->n_group;
  shared->dim_R0_2 = shared->n_vax;
  shared->dim_S_1 = shared->n_group;
  shared->dim_S_2 = shared->n_vax;
  shared->dim_s_ij_1 = shared->n_group;
  shared->dim_s_ij_2 = shared->n_group;
  shared->dim_S0_1 = shared->n_group;
  shared->dim_S0_2 = shared->n_vax;
  shared->dim_target_met_t_1 = shared->n_group;
  shared->dim_target_met_t_2 = 1;
  shared->dim_total_vaccinated_t_1 = shared->n_group;
  shared->dim_total_vaccinated_t_2 = 1;
  shared->dim_vaccination_coverage_target_1 = shared->n_group;
  shared->dim_vaccination_coverage_target_2 = shared->N_prioritisation_steps;
  shared->dim_vaccine_uptake = shared->n_group;
  shared->dim_ve_I = shared->n_vax;
  shared->dim_ve_T = shared->n_vax;
  shared->p_EE = 1 - dust::math::exp(- shared->gamma_E * shared->dt);
  shared->p_EI = 1 - dust::math::exp(- shared->gamma_E * shared->dt);
  shared->p_IdD = 1 - dust::math::exp(- shared->gamma_Id * shared->dt);
  shared->p_IrR = 1 - dust::math::exp(- shared->gamma_Ir * shared->dt);
  shared->steps_per_week = 7 / (real_type) shared->dt;
  internal.n_eligible = std::vector<real_type>(shared->dim_n_eligible);
  internal.prop_infectious = std::vector<real_type>(shared->dim_prop_infectious);
  shared->beta_z = user_get_array_fixed<real_type, 1>(user, "beta_z", shared->beta_z, {shared->dim_beta_z}, NA_REAL, NA_REAL);
  shared->dim_CFR = shared->dim_CFR_1 * shared->dim_CFR_2;
  shared->dim_D = shared->dim_D_1 * shared->dim_D_2;
  shared->dim_D0 = shared->dim_D0_1 * shared->dim_D0_2;
  shared->dim_daily_doses = shared->dim_daily_doses_1 * shared->dim_daily_doses_2;
  shared->dim_daily_doses_t = shared->dim_daily_doses_t_1 * shared->dim_daily_doses_t_2;
  shared->dim_delta_D = shared->dim_delta_D_1 * shared->dim_delta_D_2;
  shared->dim_delta_Ea = shared->dim_delta_Ea_1 * shared->dim_delta_Ea_2;
  shared->dim_delta_Ea_n_vaccination = shared->dim_delta_Ea_n_vaccination_1 * shared->dim_delta_Ea_n_vaccination_2;
  shared->dim_delta_Eb = shared->dim_delta_Eb_1 * shared->dim_delta_Eb_2;
  shared->dim_delta_Eb_n_vaccination = shared->dim_delta_Eb_n_vaccination_1 * shared->dim_delta_Eb_n_vaccination_2;
  shared->dim_delta_Id = shared->dim_delta_Id_1 * shared->dim_delta_Id_2;
  shared->dim_delta_Ir = shared->dim_delta_Ir_1 * shared->dim_delta_Ir_2;
  shared->dim_delta_R = shared->dim_delta_R_1 * shared->dim_delta_R_2;
  shared->dim_delta_R_n_vaccination = shared->dim_delta_R_n_vaccination_1 * shared->dim_delta_R_n_vaccination_2;
  shared->dim_delta_S_n_vaccination = shared->dim_delta_S_n_vaccination_1 * shared->dim_delta_S_n_vaccination_2;
  shared->dim_E = shared->dim_E_1 * shared->dim_E_2;
  shared->dim_Ea = shared->dim_Ea_1 * shared->dim_Ea_2;
  shared->dim_Ea0 = shared->dim_Ea0_1 * shared->dim_Ea0_2;
  shared->dim_Eb = shared->dim_Eb_1 * shared->dim_Eb_2;
  shared->dim_Eb0 = shared->dim_Eb0_1 * shared->dim_Eb0_2;
  shared->dim_I = shared->dim_I_1 * shared->dim_I_2;
  shared->dim_I_infectious = shared->dim_I_infectious_1 * shared->dim_I_infectious_2;
  shared->dim_Id = shared->dim_Id_1 * shared->dim_Id_2;
  shared->dim_Id0 = shared->dim_Id0_1 * shared->dim_Id0_2;
  shared->dim_Ir = shared->dim_Ir_1 * shared->dim_Ir_2;
  shared->dim_Ir0 = shared->dim_Ir0_1 * shared->dim_Ir0_2;
  shared->dim_lambda = shared->dim_lambda_1 * shared->dim_lambda_2;
  shared->dim_m = shared->dim_m_1 * shared->dim_m_2;
  shared->dim_N = shared->dim_N_1 * shared->dim_N_2;
  shared->dim_n_EaEb = shared->dim_n_EaEb_1 * shared->dim_n_EaEb_2;
  shared->dim_n_EbI = shared->dim_n_EbI_1 * shared->dim_n_EbI_2;
  shared->dim_n_EbId = shared->dim_n_EbId_1 * shared->dim_n_EbId_2;
  shared->dim_n_EbIr = shared->dim_n_EbIr_1 * shared->dim_n_EbIr_2;
  shared->dim_n_IdD = shared->dim_n_IdD_1 * shared->dim_n_IdD_2;
  shared->dim_n_IrR = shared->dim_n_IrR_1 * shared->dim_n_IrR_2;
  shared->dim_n_SEa = shared->dim_n_SEa_1 * shared->dim_n_SEa_2;
  shared->dim_n_vaccination_t_Ea = shared->dim_n_vaccination_t_Ea_1 * shared->dim_n_vaccination_t_Ea_2;
  shared->dim_n_vaccination_t_Eb = shared->dim_n_vaccination_t_Eb_1 * shared->dim_n_vaccination_t_Eb_2;
  shared->dim_n_vaccination_t_R = shared->dim_n_vaccination_t_R_1 * shared->dim_n_vaccination_t_R_2;
  shared->dim_n_vaccination_t_S = shared->dim_n_vaccination_t_S_1 * shared->dim_n_vaccination_t_S_2;
  shared->dim_p_SE = shared->dim_p_SE_1 * shared->dim_p_SE_2;
  shared->dim_prioritisation_strategy = shared->dim_prioritisation_strategy_1 * shared->dim_prioritisation_strategy_2;
  shared->dim_R = shared->dim_R_1 * shared->dim_R_2;
  shared->dim_R0 = shared->dim_R0_1 * shared->dim_R0_2;
  shared->dim_S = shared->dim_S_1 * shared->dim_S_2;
  shared->dim_s_ij = shared->dim_s_ij_1 * shared->dim_s_ij_2;
  shared->dim_S0 = shared->dim_S0_1 * shared->dim_S0_2;
  shared->dim_target_met_t = shared->dim_target_met_t_1 * shared->dim_target_met_t_2;
  shared->dim_total_vaccinated_t = shared->dim_total_vaccinated_t_1 * shared->dim_total_vaccinated_t_2;
  shared->dim_vaccination_coverage_target = shared->dim_vaccination_coverage_target_1 * shared->dim_vaccination_coverage_target_2;
  shared->vaccine_uptake = user_get_array_fixed<real_type, 1>(user, "vaccine_uptake", shared->vaccine_uptake, {shared->dim_vaccine_uptake}, NA_REAL, NA_REAL);
  shared->ve_I = user_get_array_fixed<real_type, 1>(user, "ve_I", shared->ve_I, {shared->dim_ve_I}, NA_REAL, NA_REAL);
  shared->ve_T = user_get_array_fixed<real_type, 1>(user, "ve_T", shared->ve_T, {shared->dim_ve_T}, NA_REAL, NA_REAL);
  internal.daily_doses_t = std::vector<real_type>(shared->dim_daily_doses_t);
  internal.delta_D = std::vector<real_type>(shared->dim_delta_D);
  internal.delta_Ea = std::vector<real_type>(shared->dim_delta_Ea);
  internal.delta_Ea_n_vaccination = std::vector<real_type>(shared->dim_delta_Ea_n_vaccination);
  internal.delta_Eb = std::vector<real_type>(shared->dim_delta_Eb);
  internal.delta_Eb_n_vaccination = std::vector<real_type>(shared->dim_delta_Eb_n_vaccination);
  internal.delta_Id = std::vector<real_type>(shared->dim_delta_Id);
  internal.delta_Ir = std::vector<real_type>(shared->dim_delta_Ir);
  internal.delta_R = std::vector<real_type>(shared->dim_delta_R);
  internal.delta_R_n_vaccination = std::vector<real_type>(shared->dim_delta_R_n_vaccination);
  internal.delta_S_n_vaccination = std::vector<real_type>(shared->dim_delta_S_n_vaccination);
  internal.I_infectious = std::vector<real_type>(shared->dim_I_infectious);
  shared->initial_D = std::vector<real_type>(shared->dim_D);
  shared->initial_E = std::vector<real_type>(shared->dim_E);
  shared->initial_Ea = std::vector<real_type>(shared->dim_Ea);
  shared->initial_Eb = std::vector<real_type>(shared->dim_Eb);
  shared->initial_I = std::vector<real_type>(shared->dim_I);
  shared->initial_Id = std::vector<real_type>(shared->dim_Id);
  shared->initial_Ir = std::vector<real_type>(shared->dim_Ir);
  shared->initial_N = std::vector<real_type>(shared->dim_N);
  shared->initial_R = std::vector<real_type>(shared->dim_R);
  shared->initial_S = std::vector<real_type>(shared->dim_S);
  internal.lambda = std::vector<real_type>(shared->dim_lambda);
  internal.n_EaEb = std::vector<real_type>(shared->dim_n_EaEb);
  internal.n_EbI = std::vector<real_type>(shared->dim_n_EbI);
  internal.n_EbId = std::vector<real_type>(shared->dim_n_EbId);
  internal.n_EbIr = std::vector<real_type>(shared->dim_n_EbIr);
  internal.n_IdD = std::vector<real_type>(shared->dim_n_IdD);
  internal.n_IrR = std::vector<real_type>(shared->dim_n_IrR);
  internal.n_SEa = std::vector<real_type>(shared->dim_n_SEa);
  internal.n_vaccination_t_Ea = std::vector<real_type>(shared->dim_n_vaccination_t_Ea);
  internal.n_vaccination_t_Eb = std::vector<real_type>(shared->dim_n_vaccination_t_Eb);
  internal.n_vaccination_t_R = std::vector<real_type>(shared->dim_n_vaccination_t_R);
  internal.n_vaccination_t_S = std::vector<real_type>(shared->dim_n_vaccination_t_S);
  internal.p_SE = std::vector<real_type>(shared->dim_p_SE);
  internal.s_ij = std::vector<real_type>(shared->dim_s_ij);
  internal.target_met_t = std::vector<real_type>(shared->dim_target_met_t);
  internal.total_vaccinated_t = std::vector<real_type>(shared->dim_total_vaccinated_t);
  shared->CFR = user_get_array_fixed<real_type, 2>(user, "CFR", shared->CFR, {shared->dim_CFR_1, shared->dim_CFR_2}, NA_REAL, NA_REAL);
  shared->D0 = user_get_array_fixed<real_type, 2>(user, "D0", shared->D0, {shared->dim_D0_1, shared->dim_D0_2}, NA_REAL, NA_REAL);
  shared->daily_doses = user_get_array_fixed<real_type, 2>(user, "daily_doses", shared->daily_doses, {shared->dim_daily_doses_1, shared->dim_daily_doses_2}, NA_REAL, NA_REAL);
  shared->Ea0 = user_get_array_fixed<real_type, 2>(user, "Ea0", shared->Ea0, {shared->dim_Ea0_1, shared->dim_Ea0_2}, NA_REAL, NA_REAL);
  shared->Eb0 = user_get_array_fixed<real_type, 2>(user, "Eb0", shared->Eb0, {shared->dim_Eb0_1, shared->dim_Eb0_2}, NA_REAL, NA_REAL);
  shared->Id0 = user_get_array_fixed<real_type, 2>(user, "Id0", shared->Id0, {shared->dim_Id0_1, shared->dim_Id0_2}, NA_REAL, NA_REAL);
  shared->Ir0 = user_get_array_fixed<real_type, 2>(user, "Ir0", shared->Ir0, {shared->dim_Ir0_1, shared->dim_Ir0_2}, NA_REAL, NA_REAL);
  shared->m = user_get_array_fixed<real_type, 2>(user, "m", shared->m, {shared->dim_m_1, shared->dim_m_2}, NA_REAL, NA_REAL);
  shared->offset_variable_D = shared->dim_Ea + shared->dim_Eb + shared->dim_Id + shared->dim_Ir + shared->dim_R + shared->dim_S + 25;
  shared->offset_variable_E = shared->dim_D + shared->dim_Ea + shared->dim_Eb + shared->dim_Id + shared->dim_Ir + shared->dim_R + shared->dim_S + 25;
  shared->offset_variable_Ea = shared->dim_S + 25;
  shared->offset_variable_Eb = shared->dim_Ea + shared->dim_S + 25;
  shared->offset_variable_I = shared->dim_D + shared->dim_E + shared->dim_Ea + shared->dim_Eb + shared->dim_Id + shared->dim_Ir + shared->dim_R + shared->dim_S + 25;
  shared->offset_variable_Id = shared->dim_Ea + shared->dim_Eb + shared->dim_Ir + shared->dim_S + 25;
  shared->offset_variable_Ir = shared->dim_Ea + shared->dim_Eb + shared->dim_S + 25;
  shared->offset_variable_N = shared->dim_D + shared->dim_E + shared->dim_Ea + shared->dim_Eb + shared->dim_I + shared->dim_Id + shared->dim_Ir + shared->dim_R + shared->dim_S + 25;
  shared->offset_variable_R = shared->dim_Ea + shared->dim_Eb + shared->dim_Id + shared->dim_Ir + shared->dim_S + 25;
  shared->prioritisation_strategy = user_get_array_fixed<real_type, 2>(user, "prioritisation_strategy", shared->prioritisation_strategy, {shared->dim_prioritisation_strategy_1, shared->dim_prioritisation_strategy_2}, NA_REAL, NA_REAL);
  shared->R0 = user_get_array_fixed<real_type, 2>(user, "R0", shared->R0, {shared->dim_R0_1, shared->dim_R0_2}, NA_REAL, NA_REAL);
  shared->S0 = user_get_array_fixed<real_type, 2>(user, "S0", shared->S0, {shared->dim_S0_1, shared->dim_S0_2}, NA_REAL, NA_REAL);
  shared->vaccination_coverage_target = user_get_array_fixed<real_type, 2>(user, "vaccination_coverage_target", shared->vaccination_coverage_target, {shared->dim_vaccination_coverage_target_1, shared->dim_vaccination_coverage_target_2}, NA_REAL, NA_REAL);
  for (int i = 1; i <= shared->dim_D_1; ++i) {
    for (int j = 1; j <= shared->dim_D_2; ++j) {
      shared->initial_D[i - 1 + shared->dim_D_1 * (j - 1)] = shared->D0[shared->dim_D0_1 * (j - 1) + i - 1];
    }
  }
  shared->initial_D_tot = odin_sum2<real_type>(shared->D0.data(), 0, shared->dim_D0_1, 0, shared->dim_D0_2, shared->dim_D0_1);
  for (int i = 1; i <= shared->dim_E_1; ++i) {
    for (int j = 1; j <= shared->dim_E_2; ++j) {
      shared->initial_E[i - 1 + shared->dim_E_1 * (j - 1)] = shared->Ea0[shared->dim_Ea0_1 * (j - 1) + i - 1] + shared->Eb0[shared->dim_Eb0_1 * (j - 1) + i - 1];
    }
  }
  shared->initial_E_tot = odin_sum2<real_type>(shared->Ea0.data(), 0, shared->dim_Ea0_1, 0, shared->dim_Ea0_2, shared->dim_Ea0_1) + odin_sum2<real_type>(shared->Eb0.data(), 0, shared->dim_Eb0_1, 0, shared->dim_Eb0_2, shared->dim_Eb0_1);
  for (int i = 1; i <= shared->dim_Ea_1; ++i) {
    for (int j = 1; j <= shared->dim_Ea_2; ++j) {
      shared->initial_Ea[i - 1 + shared->dim_Ea_1 * (j - 1)] = shared->Ea0[shared->dim_Ea0_1 * (j - 1) + i - 1];
    }
  }
  for (int i = 1; i <= shared->dim_Eb_1; ++i) {
    for (int j = 1; j <= shared->dim_Eb_2; ++j) {
      shared->initial_Eb[i - 1 + shared->dim_Eb_1 * (j - 1)] = shared->Eb0[shared->dim_Eb0_1 * (j - 1) + i - 1];
    }
  }
  for (int i = 1; i <= shared->dim_I_1; ++i) {
    for (int j = 1; j <= shared->dim_I_2; ++j) {
      shared->initial_I[i - 1 + shared->dim_I_1 * (j - 1)] = shared->Ir0[shared->dim_Ir0_1 * (j - 1) + i - 1] + shared->Id0[shared->dim_Id0_1 * (j - 1) + i - 1];
    }
  }
  shared->initial_I_tot = odin_sum2<real_type>(shared->Ir0.data(), 0, shared->dim_Ir0_1, 0, shared->dim_Ir0_2, shared->dim_Ir0_1) + odin_sum2<real_type>(shared->Id0.data(), 0, shared->dim_Id0_1, 0, shared->dim_Id0_2, shared->dim_Id0_1);
  for (int i = 1; i <= shared->dim_Id_1; ++i) {
    for (int j = 1; j <= shared->dim_Id_2; ++j) {
      shared->initial_Id[i - 1 + shared->dim_Id_1 * (j - 1)] = shared->Id0[shared->dim_Id0_1 * (j - 1) + i - 1];
    }
  }
  for (int i = 1; i <= shared->dim_Ir_1; ++i) {
    for (int j = 1; j <= shared->dim_Ir_2; ++j) {
      shared->initial_Ir[i - 1 + shared->dim_Ir_1 * (j - 1)] = shared->Ir0[shared->dim_Ir0_1 * (j - 1) + i - 1];
    }
  }
  for (int i = 1; i <= shared->dim_N_1; ++i) {
    for (int j = 1; j <= shared->dim_N_2; ++j) {
      shared->initial_N[i - 1 + shared->dim_N_1 * (j - 1)] = shared->S0[shared->dim_S0_1 * (j - 1) + i - 1] + shared->Ea0[shared->dim_Ea0_1 * (j - 1) + i - 1] + shared->Eb0[shared->dim_Eb0_1 * (j - 1) + i - 1] + shared->Ir0[shared->dim_Ir0_1 * (j - 1) + i - 1] + shared->Id0[shared->dim_Id0_1 * (j - 1) + i - 1] + shared->R0[shared->dim_R0_1 * (j - 1) + i - 1] + shared->D0[shared->dim_D0_1 * (j - 1) + i - 1];
    }
  }
  shared->initial_N_tot = odin_sum2<real_type>(shared->S0.data(), 0, shared->dim_S0_1, 0, shared->dim_S0_2, shared->dim_S0_1) + odin_sum2<real_type>(shared->Ea0.data(), 0, shared->dim_Ea0_1, 0, shared->dim_Ea0_2, shared->dim_Ea0_1) + odin_sum2<real_type>(shared->Eb0.data(), 0, shared->dim_Eb0_1, 0, shared->dim_Eb0_2, shared->dim_Eb0_1) + odin_sum2<real_type>(shared->Ir0.data(), 0, shared->dim_Ir0_1, 0, shared->dim_Ir0_2, shared->dim_Ir0_1) + odin_sum2<real_type>(shared->Id0.data(), 0, shared->dim_Id0_1, 0, shared->dim_Id0_2, shared->dim_Id0_1) + odin_sum2<real_type>(shared->R0.data(), 0, shared->dim_R0_1, 0, shared->dim_R0_2, shared->dim_R0_1) + odin_sum2<real_type>(shared->D0.data(), 0, shared->dim_D0_1, 0, shared->dim_D0_2, shared->dim_D0_1);
  for (int i = 1; i <= shared->dim_R_1; ++i) {
    for (int j = 1; j <= shared->dim_R_2; ++j) {
      shared->initial_R[i - 1 + shared->dim_R_1 * (j - 1)] = shared->R0[shared->dim_R0_1 * (j - 1) + i - 1];
    }
  }
  shared->initial_R_tot = odin_sum2<real_type>(shared->R0.data(), 0, shared->dim_R0_1, 0, shared->dim_R0_2, shared->dim_R0_1);
  for (int i = 1; i <= shared->dim_S_1; ++i) {
    for (int j = 1; j <= shared->dim_S_2; ++j) {
      shared->initial_S[i - 1 + shared->dim_S_1 * (j - 1)] = shared->S0[shared->dim_S0_1 * (j - 1) + i - 1];
    }
  }
  shared->initial_S_tot = odin_sum2<real_type>(shared->S0.data(), 0, shared->dim_S0_1, 0, shared->dim_S0_2, shared->dim_S0_1);
  return dust::pars_type<model_targeted_vax>(shared, internal);
}
template <>
cpp11::sexp dust_info<model_targeted_vax>(const dust::pars_type<model_targeted_vax>& pars) {
  const std::shared_ptr<const model_targeted_vax::shared_type> shared = pars.shared;
  cpp11::writable::strings nms({"time", "prioritisation_step", "cases", "deaths", "cases_0_5", "cases_5_15", "cases_15_plus", "cases_PBS", "cases_SW", "deaths_0_5", "deaths_5_15", "deaths_15_plus", "deaths_PBS", "deaths_SW", "vax_given_S", "vax_given_Ea", "vax_given_Eb", "vax_given_R", "S_tot", "E_tot", "I_tot", "R_tot", "D_tot", "N_tot", "total_vax", "S", "Ea", "Eb", "Ir", "Id", "R", "D", "E", "I", "N"});
  cpp11::writable::list dim(35);
  dim[0] = cpp11::writable::integers({1});
  dim[1] = cpp11::writable::integers({1});
  dim[2] = cpp11::writable::integers({1});
  dim[3] = cpp11::writable::integers({1});
  dim[4] = cpp11::writable::integers({1});
  dim[5] = cpp11::writable::integers({1});
  dim[6] = cpp11::writable::integers({1});
  dim[7] = cpp11::writable::integers({1});
  dim[8] = cpp11::writable::integers({1});
  dim[9] = cpp11::writable::integers({1});
  dim[10] = cpp11::writable::integers({1});
  dim[11] = cpp11::writable::integers({1});
  dim[12] = cpp11::writable::integers({1});
  dim[13] = cpp11::writable::integers({1});
  dim[14] = cpp11::writable::integers({1});
  dim[15] = cpp11::writable::integers({1});
  dim[16] = cpp11::writable::integers({1});
  dim[17] = cpp11::writable::integers({1});
  dim[18] = cpp11::writable::integers({1});
  dim[19] = cpp11::writable::integers({1});
  dim[20] = cpp11::writable::integers({1});
  dim[21] = cpp11::writable::integers({1});
  dim[22] = cpp11::writable::integers({1});
  dim[23] = cpp11::writable::integers({1});
  dim[24] = cpp11::writable::integers({1});
  dim[25] = cpp11::writable::integers({shared->dim_S_1, shared->dim_S_2});
  dim[26] = cpp11::writable::integers({shared->dim_Ea_1, shared->dim_Ea_2});
  dim[27] = cpp11::writable::integers({shared->dim_Eb_1, shared->dim_Eb_2});
  dim[28] = cpp11::writable::integers({shared->dim_Ir_1, shared->dim_Ir_2});
  dim[29] = cpp11::writable::integers({shared->dim_Id_1, shared->dim_Id_2});
  dim[30] = cpp11::writable::integers({shared->dim_R_1, shared->dim_R_2});
  dim[31] = cpp11::writable::integers({shared->dim_D_1, shared->dim_D_2});
  dim[32] = cpp11::writable::integers({shared->dim_E_1, shared->dim_E_2});
  dim[33] = cpp11::writable::integers({shared->dim_I_1, shared->dim_I_2});
  dim[34] = cpp11::writable::integers({shared->dim_N_1, shared->dim_N_2});
  dim.names() = nms;
  cpp11::writable::list index(35);
  index[0] = cpp11::writable::integers({1});
  index[1] = cpp11::writable::integers({2});
  index[2] = cpp11::writable::integers({3});
  index[3] = cpp11::writable::integers({4});
  index[4] = cpp11::writable::integers({5});
  index[5] = cpp11::writable::integers({6});
  index[6] = cpp11::writable::integers({7});
  index[7] = cpp11::writable::integers({8});
  index[8] = cpp11::writable::integers({9});
  index[9] = cpp11::writable::integers({10});
  index[10] = cpp11::writable::integers({11});
  index[11] = cpp11::writable::integers({12});
  index[12] = cpp11::writable::integers({13});
  index[13] = cpp11::writable::integers({14});
  index[14] = cpp11::writable::integers({15});
  index[15] = cpp11::writable::integers({16});
  index[16] = cpp11::writable::integers({17});
  index[17] = cpp11::writable::integers({18});
  index[18] = cpp11::writable::integers({19});
  index[19] = cpp11::writable::integers({20});
  index[20] = cpp11::writable::integers({21});
  index[21] = cpp11::writable::integers({22});
  index[22] = cpp11::writable::integers({23});
  index[23] = cpp11::writable::integers({24});
  index[24] = cpp11::writable::integers({25});
  index[25] = integer_sequence(26, shared->dim_S);
  index[26] = integer_sequence(shared->offset_variable_Ea + 1, shared->dim_Ea);
  index[27] = integer_sequence(shared->offset_variable_Eb + 1, shared->dim_Eb);
  index[28] = integer_sequence(shared->offset_variable_Ir + 1, shared->dim_Ir);
  index[29] = integer_sequence(shared->offset_variable_Id + 1, shared->dim_Id);
  index[30] = integer_sequence(shared->offset_variable_R + 1, shared->dim_R);
  index[31] = integer_sequence(shared->offset_variable_D + 1, shared->dim_D);
  index[32] = integer_sequence(shared->offset_variable_E + 1, shared->dim_E);
  index[33] = integer_sequence(shared->offset_variable_I + 1, shared->dim_I);
  index[34] = integer_sequence(shared->offset_variable_N + 1, shared->dim_N);
  index.names() = nms;
  size_t len = shared->offset_variable_N + shared->dim_N;
  using namespace cpp11::literals;
  return cpp11::writable::list({
           "dim"_nm = dim,
           "len"_nm = len,
           "index"_nm = index});
}
}
