# Generated by cpp11: do not edit by hand

dust_model_generic_vax_gpu_info <- function() {
  .Call(`_mpoxseir_dust_model_generic_vax_gpu_info`)
}

dust_cpu_model_generic_vax_alloc <- function(r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_alloc`, r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control)
}

dust_cpu_model_generic_vax_capabilities <- function() {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_capabilities`)
}

dust_cpu_model_generic_vax_run <- function(ptr, r_time_end) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_run`, ptr, r_time_end)
}

dust_cpu_model_generic_vax_simulate <- function(ptr, time_end) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_simulate`, ptr, time_end)
}

dust_cpu_model_generic_vax_run_adjoint <- function(ptr) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_run_adjoint`, ptr)
}

dust_cpu_model_generic_vax_set_index <- function(ptr, r_index) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_set_index`, ptr, r_index)
}

dust_cpu_model_generic_vax_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_model_generic_vax_state <- function(ptr, r_index) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_state`, ptr, r_index)
}

dust_cpu_model_generic_vax_time <- function(ptr) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_time`, ptr)
}

dust_cpu_model_generic_vax_reorder <- function(ptr, r_index) {
  invisible(.Call(`_mpoxseir_dust_cpu_model_generic_vax_reorder`, ptr, r_index))
}

dust_cpu_model_generic_vax_resample <- function(ptr, r_weights) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_resample`, ptr, r_weights)
}

dust_cpu_model_generic_vax_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_rng_state`, ptr, first_only, last_only)
}

dust_cpu_model_generic_vax_set_rng_state <- function(ptr, rng_state) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_set_rng_state`, ptr, rng_state)
}

dust_cpu_model_generic_vax_set_data <- function(ptr, data, shared) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_set_data`, ptr, data, shared)
}

dust_cpu_model_generic_vax_compare_data <- function(ptr) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_compare_data`, ptr)
}

dust_cpu_model_generic_vax_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_model_generic_vax_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_mpoxseir_dust_cpu_model_generic_vax_set_n_threads`, ptr, n_threads))
}

dust_cpu_model_generic_vax_n_state <- function(ptr) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_n_state`, ptr)
}

dust_cpu_model_generic_vax_set_stochastic_schedule <- function(ptr, time) {
  invisible(.Call(`_mpoxseir_dust_cpu_model_generic_vax_set_stochastic_schedule`, ptr, time))
}

dust_cpu_model_generic_vax_ode_statistics <- function(ptr) {
  .Call(`_mpoxseir_dust_cpu_model_generic_vax_ode_statistics`, ptr)
}

dust2_system_model_targeted_vax_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_model_targeted_vax_run_to_time <- function(ptr, r_time) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_run_to_time`, ptr, r_time)
}

dust2_system_model_targeted_vax_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_model_targeted_vax_time <- function(ptr) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_time`, ptr)
}

dust2_system_model_targeted_vax_set_state_initial <- function(ptr) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_set_state_initial`, ptr)
}

dust2_system_model_targeted_vax_set_state <- function(ptr, r_state, preserve_group_dimension) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_set_state`, ptr, r_state, preserve_group_dimension)
}

dust2_system_model_targeted_vax_reorder <- function(ptr, r_index) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_reorder`, ptr, r_index)
}

dust2_system_model_targeted_vax_rng_state <- function(ptr) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_rng_state`, ptr)
}

dust2_system_model_targeted_vax_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_set_rng_state`, ptr, r_rng_state)
}

dust2_system_model_targeted_vax_set_time <- function(ptr, r_time) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_set_time`, ptr, r_time)
}

dust2_system_model_targeted_vax_update_pars <- function(ptr, pars) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_update_pars`, ptr, pars)
}

dust2_system_model_targeted_vax_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_model_targeted_vax_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_index_state) {
  .Call(`_mpoxseir_dust2_unfilter_model_targeted_vax_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_index_state)
}

dust2_filter_model_targeted_vax_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_index_state, r_seed) {
  .Call(`_mpoxseir_dust2_filter_model_targeted_vax_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_index_state, r_seed)
}

dust2_system_model_targeted_vax_compare_data <- function(ptr, r_data, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_mpoxseir_dust2_system_model_targeted_vax_compare_data`, ptr, r_data, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_model_targeted_vax_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_mpoxseir_dust2_unfilter_model_targeted_vax_update_pars`, ptr, r_pars, r_index_group)
}

dust2_unfilter_model_targeted_vax_run <- function(ptr, r_initial, save_history, adjoint, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_mpoxseir_dust2_unfilter_model_targeted_vax_run`, ptr, r_initial, save_history, adjoint, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_model_targeted_vax_last_history <- function(ptr, r_index_group, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_mpoxseir_dust2_unfilter_model_targeted_vax_last_history`, ptr, r_index_group, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_model_targeted_vax_last_state <- function(ptr, r_index_group, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_mpoxseir_dust2_unfilter_model_targeted_vax_last_state`, ptr, r_index_group, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_model_targeted_vax_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_mpoxseir_dust2_filter_model_targeted_vax_update_pars`, ptr, r_pars, r_index_group)
}

dust2_filter_model_targeted_vax_run <- function(ptr, r_initial, save_history, adjoint, index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_mpoxseir_dust2_filter_model_targeted_vax_run`, ptr, r_initial, save_history, adjoint, index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_model_targeted_vax_last_history <- function(ptr, r_index_group, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_mpoxseir_dust2_filter_model_targeted_vax_last_history`, ptr, r_index_group, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_model_targeted_vax_last_state <- function(ptr, r_index_group, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_mpoxseir_dust2_filter_model_targeted_vax_last_state`, ptr, r_index_group, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_model_targeted_vax_rng_state <- function(ptr) {
  .Call(`_mpoxseir_dust2_filter_model_targeted_vax_rng_state`, ptr)
}

dust2_filter_model_targeted_vax_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_mpoxseir_dust2_filter_model_targeted_vax_set_rng_state`, ptr, r_rng_state)
}
