## Generated by dust2 (version 0.2.3) - do not edit
model_targeted_vax <- structure(
  function() get("model_targeted_vax"),
  class = "dust_system_generator",
  name = "model_targeted_vax",
  package = "mpoxseir",
  path = NULL,
  parameters = data.frame(
    name = c("children_ind_raw", "adults_ind_raw", "daily_doses_children_value", "daily_doses_children_time", "daily_doses_adults_value", "daily_doses_adults_time", "N_prioritisation_steps_children", "N_prioritisation_steps_adults", "prioritisation_strategy_children", "prioritisation_strategy_adults", "m_gen_pop", "m_sex", "S0", "Ea0", "Eb0", "Ir0", "Id0", "R0", "D0", "beta_h", "beta_s", "beta_z", "gamma_E", "gamma_Ir", "gamma_Id", "CFR", "ve_T", "ve_I", "n_vax", "n_group", "exp_noise"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "int", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE),
    required = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE),
    rank = c(1L, 1L, 2L, 1L, 2L, 1L, 0L, 0L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 0L, 0L, 1L, 0L, 0L, 0L, 2L, 1L, 2L, 0L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = 1)
