## Generated by dust2 (version 0.2.2) - do not edit
model_targeted_vax <- structure(
  function() get("model_targeted_vax"),
  class = "dust_system_generator",
  name = "model_targeted_vax",
  package = "mpoxseir",
  path = NULL,
  parameters = NULL,
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = 1)
